H = $$LITERAL_HASH
OPTHW = "// Autogenerated by hardware.pri; do not edit!"

include($$PWD/core/core.pri)
include($$PWD/core/clock/clock.pri)
include($$PWD/core/communication/communication.pri)
include($$PWD/core/ftmwdigitizer/ftmwdigitizer.pri)
include($$PWD/optional/chirpsource/chirpsource.pri)
include($$PWD/optional/ioboard/ioboard.pri)
include($$PWD/optional/pulsegenerator/pulsegenerator.pri)
include($$PWD/optional/flowcontroller/flowcontroller.pri)
include($$PWD/optional/gpibcontroller/gpibcontroller.pri)
include($$PWD/optional/pressurecontroller/pressurecontroller.pri)
include($$PWD/optional/tempcontroller/tempcontroller.pri)


write_file( $$PWD/opthw_h.h, OPTHW)
HEADERS += $$PWD/opthw_h.h
