// Autogenerated by hardware.pri; do not edit!
#include <hardware/optional/ioboard/virtualioboard.h>
#include <hardware/optional/pulsegenerator/virtualpulsegenerator.h>
#include <hardware/optional/flowcontroller/virtualflowcontroller.h>
#include <hardware/optional/tempcontroller/virtualtempcontroller.h>
