H = $$LITERAL_HASH
LIFHW = "// Autogenerated by hardware.pri; do not edit!"

include($$PWD/lifdigitizer/lifdigitizer.pri)
include($$PWD/liflaser/liflaser.pri)

write_file( $$PWD/lifhw_h.h, LIFHW)
HEADERS += $$PWD/lifhw_h.h
