# Data layer sources for Blackchirp Viewer
# Includes all data structures, analysis, storage, and processing components
# Excludes acquisition-specific components

SOURCES += $$PWD/../src/data/loghandler.cpp \
    $$PWD/../src/data/analysis/analysis.cpp \
    $$PWD/../src/data/analysis/ft.cpp \
    $$PWD/../src/data/analysis/ftworker.cpp \
    $$PWD/../src/data/analysis/peakfinder.cpp \
    $$PWD/../src/data/bcglobals.cpp \
    $$PWD/../src/data/experiment/chirpconfig.cpp \
    $$PWD/../src/data/experiment/digitizerconfig.cpp \
    $$PWD/../src/data/experiment/experiment.cpp \
    $$PWD/../src/data/experiment/experimentobjective.cpp \
    $$PWD/../src/data/experiment/experimentvalidator.cpp \
    $$PWD/../src/data/experiment/fid.cpp \
    $$PWD/../src/data/experiment/ftmwconfig.cpp \
    $$PWD/../src/data/experiment/ftmwconfigtypes.cpp \
    $$PWD/../src/data/experiment/overlaybase.cpp \
    $$PWD/../src/data/experiment/overlaytypes.cpp \
    $$PWD/../src/data/experiment/catalogdata.cpp \
    $$PWD/../src/data/processing/parsers/fileparser.cpp \
    $$PWD/../src/data/processing/parsers/catalogparser.cpp \
    $$PWD/../src/data/processing/parsers/fileparserregistry.cpp \
    $$PWD/../src/data/processing/parsers/spcatparser.cpp \
    $$PWD/../src/data/processing/parsers/xiamparser.cpp \
    $$PWD/../src/data/processing/parsers/genericxyparser.cpp \
    $$PWD/../src/data/processing/parsers/genericxydata.cpp \
    $$PWD/../src/data/experiment/rfconfig.cpp \
    $$PWD/../src/data/model/exptsummarymodel.cpp \
    $$PWD/../src/data/model/overlaytablemodel.cpp \
    $$PWD/../src/data/model/peaklistmodel.cpp \
    $$PWD/../src/data/model/validationmodel.cpp \
    $$PWD/../src/data/processing/overlayoperation.cpp \
    $$PWD/../src/data/processing/overlayprocessmanager.cpp \
    $$PWD/../src/data/storage/auxdatastorage.cpp \
    $$PWD/../src/data/storage/blackchirpcsv.cpp \
    $$PWD/../src/data/storage/datastoragebase.cpp \
    $$PWD/../src/data/storage/fidmultistorage.cpp \
    $$PWD/../src/data/storage/fidpeakupstorage.cpp \
    $$PWD/../src/data/storage/fidsinglestorage.cpp \
    $$PWD/../src/data/storage/fidstoragebase.cpp \
    $$PWD/../src/data/storage/headerstorage.cpp \
    $$PWD/../src/data/storage/overlaystorage.cpp \
    $$PWD/../src/data/storage/settingsstorage.cpp \
    $$PWD/../src/hardware/optional/pulsegenerator/pulsegenconfig.cpp \
    $$PWD/../src/hardware/optional/flowcontroller/flowconfig.cpp \
    $$PWD/../src/hardware/optional/ioboard/ioboardconfig.cpp \
    $$PWD/../src/hardware/optional/pressurecontroller/pressurecontrollerconfig.cpp \
    $$PWD/../src/hardware/optional/tempcontroller/temperaturecontrollerconfig.cpp \
    $$PWD/../src/hardware/core/ftmwdigitizer/ftmwdigitizerconfig.cpp

HEADERS += $$PWD/../src/data/loghandler.h \
    $$PWD/../src/data/analysis/analysis.h \
    $$PWD/../src/data/analysis/ft.h \
    $$PWD/../src/data/analysis/ftworker.h \
    $$PWD/../src/data/analysis/peakfinder.h \
    $$PWD/../src/data/bcglobals.h \
    $$PWD/../src/data/experiment/chirpconfig.h \
    $$PWD/../src/data/experiment/digitizerconfig.h \
    $$PWD/../src/data/experiment/experiment.h \
    $$PWD/../src/data/experiment/experimentobjective.h \
    $$PWD/../src/data/experiment/experimentvalidator.h \
    $$PWD/../src/data/experiment/fid.h \
    $$PWD/../src/data/experiment/ftmwconfig.h \
    $$PWD/../src/data/experiment/ftmwconfigtypes.h \
    $$PWD/../src/data/experiment/overlaybase.h \
    $$PWD/../src/data/experiment/overlaytypes.h \
    $$PWD/../src/data/experiment/catalogdata.h \
    $$PWD/../src/data/processing/parsers/fileparser.h \
    $$PWD/../src/data/processing/parsers/catalogparser.h \
    $$PWD/../src/data/processing/parsers/fileparserregistry.h \
    $$PWD/../src/data/processing/parsers/spcatparser.h \
    $$PWD/../src/data/processing/parsers/xiamparser.h \
    $$PWD/../src/data/processing/parsers/genericxyparser.h \
    $$PWD/../src/data/processing/parsers/genericxydata.h \
    $$PWD/../src/data/experiment/rfconfig.h \
    $$PWD/../src/data/model/exptsummarymodel.h \
    $$PWD/../src/data/model/overlaytablemodel.h \
    $$PWD/../src/data/model/peaklistmodel.h \
    $$PWD/../src/data/model/validationmodel.h \
    $$PWD/../src/data/processing/overlayoperation.h \
    $$PWD/../src/data/processing/overlayprocessmanager.h \
    $$PWD/../src/data/storage/auxdatastorage.h \
    $$PWD/../src/data/storage/blackchirpcsv.h \
    $$PWD/../src/data/storage/datastoragebase.h \
    $$PWD/../src/data/storage/fidmultistorage.h \
    $$PWD/../src/data/storage/fidpeakupstorage.h \
    $$PWD/../src/data/storage/fidsinglestorage.h \
    $$PWD/../src/data/storage/fidstoragebase.h \
    $$PWD/../src/data/storage/headerstorage.h \
    $$PWD/../src/data/storage/overlaystorage.h \
    $$PWD/../src/data/storage/settingsstorage.h \
    $$PWD/../src/hardware/optional/pulsegenerator/pulsegenconfig.h \
    $$PWD/../src/hardware/optional/flowcontroller/flowconfig.h \
    $$PWD/../src/hardware/optional/ioboard/ioboardconfig.h \
    $$PWD/../src/hardware/optional/pressurecontroller/pressurecontrollerconfig.h \
    $$PWD/../src/hardware/optional/tempcontroller/temperaturecontrollerconfig.h \
    $$PWD/../src/hardware/core/ftmwdigitizer/ftmwdigitizerconfig.h